# Use a base image with your desired Python version
FROM python:3.10.12

# Set the working directory in the container
WORKDIR /home/pkn/ecompipeline

# Copy the requirements file into the container
COPY requirements.txt /home/pkn/ecompipeline/

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the DAG and scripts into the container
COPY dags /home/pkn/ecompipeline/dags
COPY scripts /home/pkn/ecompipeline/scripts