apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: your-airflow-image:tag
          volumeMounts:
            - name: airflow-config
              mountPath: /home/user/airflow_project/scripts
          # Add other container settings
      volumes:
        - name: airflow-config
          persistentVolumeClaim:
            claimName: airflow-config-pvc
