apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecompipeline
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecompipeline
    spec:
      containers:
        - name: ecompipeline
          image: ecompipeline-image:latest
          volumeMounts:
            - name: ecompipeline-config-volume
              mountPath: /home/pkn/ecompipeline/config
          # Add other container settings
      volumes:
        - name: ecompipeline-config-volume
          persistentVolumeClaim:
            claimName: ecompipeline-config-pvc
