apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecompipeline-config-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/pkn/ecompipeline/config # Path on the host machine where your config files are stored